//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2", IsNullable=false)]
public partial class VOTABLE {
    
    private anyTEXT dESCRIPTIONField;
    
    private object[] dEFINITIONSField;
    
    private object[] itemsField;
    
    private Resource[] rESOURCEField;
    
    private Info[] iNFOField;
    
    private string idField;
    
    private VOTABLEVersion versionField;
    
    private bool versionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public anyTEXT DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("COOSYS", typeof(CoordinateSystem), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PARAM", typeof(Param), IsNullable=false)]
    public object[] DEFINITIONS {
        get {
            return this.dEFINITIONSField;
        }
        set {
            this.dEFINITIONSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(CoordinateSystem), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(Group), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("INFO", typeof(Info), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(Param), Order=2)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RESOURCE", Order=3)]
    public Resource[] RESOURCE {
        get {
            return this.rESOURCEField;
        }
        set {
            this.rESOURCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO", Order=4)]
    public Info[] INFO {
        get {
            return this.iNFOField;
        }
        set {
            this.iNFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VOTABLEVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool versionSpecified {
        get {
            return this.versionFieldSpecified;
        }
        set {
            this.versionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class anyTEXT {
    
    private System.Xml.XmlNode[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class FITS {
    
    private Stream sTREAMField;
    
    private string extnumField;
    
    /// <remarks/>
    public Stream STREAM {
        get {
            return this.sTREAMField;
        }
        set {
            this.sTREAMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string extnum {
        get {
            return this.extnumField;
        }
        set {
            this.extnumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Stream {
    
    private StreamType typeField;
    
    private string hrefField;
    
    private StreamActuate actuateField;
    
    private encodingType encodingField;
    
    private System.DateTime expiresField;
    
    private bool expiresFieldSpecified;
    
    private string rightsField;
    
    private string valueField;
    
    public Stream() {
        this.typeField = StreamType.locator;
        this.actuateField = StreamActuate.onRequest;
        this.encodingField = encodingType.none;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(StreamType.locator)]
    public StreamType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(StreamActuate.onRequest)]
    public StreamActuate actuate {
        get {
            return this.actuateField;
        }
        set {
            this.actuateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(encodingType.none)]
    public encodingType encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime expires {
        get {
            return this.expiresField;
        }
        set {
            this.expiresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expiresSpecified {
        get {
            return this.expiresFieldSpecified;
        }
        set {
            this.expiresFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string rights {
        get {
            return this.rightsField;
        }
        set {
            this.rightsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum StreamType {
    
    /// <remarks/>
    locator,
    
    /// <remarks/>
    other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum StreamActuate {
    
    /// <remarks/>
    onLoad,
    
    /// <remarks/>
    onRequest,
    
    /// <remarks/>
    other,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum encodingType {
    
    /// <remarks/>
    gzip,
    
    /// <remarks/>
    base64,
    
    /// <remarks/>
    dynamic,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Binary {
    
    private Stream sTREAMField;
    
    /// <remarks/>
    public Stream STREAM {
        get {
            return this.sTREAMField;
        }
        set {
            this.sTREAMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class TableData {
    
    private Tr[] trField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TR")]
    public Tr[] TR {
        get {
            return this.trField;
        }
        set {
            this.trField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Tr {
    
    private Td[] tdField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TD")]
    public Td[] TD {
        get {
            return this.tdField;
        }
        set {
            this.tdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Td {
    
    private encodingType encodingField;
    
    private bool encodingFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public encodingType encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool encodingSpecified {
        get {
            return this.encodingFieldSpecified;
        }
        set {
            this.encodingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Data {
    
    private object itemField;
    
    private Info[] iNFOField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BINARY", typeof(Binary))]
    [System.Xml.Serialization.XmlElementAttribute("FITS", typeof(FITS))]
    [System.Xml.Serialization.XmlElementAttribute("TABLEDATA", typeof(TableData))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO")]
    public Info[] INFO {
        get {
            return this.iNFOField;
        }
        set {
            this.iNFOField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Info {
    
    private string idField;
    
    private string nameField;
    
    private string valueField;
    
    private string unitField;
    
    private string xtypeField;
    
    private string refField;
    
    private string ucdField;
    
    private string utypeField;
    
    private string valueField1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string xtype {
        get {
            return this.xtypeField;
        }
        set {
            this.xtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Table {
    
    private anyTEXT dESCRIPTIONField;
    
    private Info[] iNFOField;
    
    private object[] itemsField;
    
    private Link[] lINKField;
    
    private Data dATAField;
    
    private Info[] iNFO1Field;
    
    private string idField;
    
    private string nameField;
    
    private string refField;
    
    private string ucdField;
    
    private string utypeField;
    
    private string nrowsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public anyTEXT DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO", Order=1)]
    public Info[] INFO {
        get {
            return this.iNFOField;
        }
        set {
            this.iNFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELD", typeof(Field), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(Group), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(Param), Order=2)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LINK", Order=3)]
    public Link[] LINK {
        get {
            return this.lINKField;
        }
        set {
            this.lINKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public Data DATA {
        get {
            return this.dATAField;
        }
        set {
            this.dATAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO", Order=5)]
    public Info[] INFO1 {
        get {
            return this.iNFO1Field;
        }
        set {
            this.iNFO1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string nrows {
        get {
            return this.nrowsField;
        }
        set {
            this.nrowsField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Param))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Field {
    
    private anyTEXT dESCRIPTIONField;
    
    private Values vALUESField;
    
    private Link[] lINKField;
    
    private string idField;
    
    private string unitField;
    
    private dataType datatypeField;
    
    private string precisionField;
    
    private string widthField;
    
    private string xtypeField;
    
    private string refField;
    
    private string nameField;
    
    private string ucdField;
    
    private string utypeField;
    
    private string arraysizeField;
    
    private FieldType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    public anyTEXT DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    public Values VALUES {
        get {
            return this.vALUESField;
        }
        set {
            this.vALUESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LINK")]
    public Link[] LINK {
        get {
            return this.lINKField;
        }
        set {
            this.lINKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public dataType datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string precision {
        get {
            return this.precisionField;
        }
        set {
            this.precisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string xtype {
        get {
            return this.xtypeField;
        }
        set {
            this.xtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arraysize {
        get {
            return this.arraysizeField;
        }
        set {
            this.arraysizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public FieldType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Values {
    
    private Min mINField;
    
    private Max mAXField;
    
    private Option[] oPTIONField;
    
    private string idField;
    
    private ValuesType typeField;
    
    private string nullField;
    
    private string refField;
    
    public Values() {
        this.typeField = ValuesType.legal;
    }
    
    /// <remarks/>
    public Min MIN {
        get {
            return this.mINField;
        }
        set {
            this.mINField = value;
        }
    }
    
    /// <remarks/>
    public Max MAX {
        get {
            return this.mAXField;
        }
        set {
            this.mAXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OPTION")]
    public Option[] OPTION {
        get {
            return this.oPTIONField;
        }
        set {
            this.oPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ValuesType.legal)]
    public ValuesType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string @null {
        get {
            return this.nullField;
        }
        set {
            this.nullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Min {
    
    private string valueField;
    
    private yesno inclusiveField;
    
    public Min() {
        this.inclusiveField = yesno.yes;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(yesno.yes)]
    public yesno inclusive {
        get {
            return this.inclusiveField;
        }
        set {
            this.inclusiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum yesno {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Max {
    
    private string valueField;
    
    private yesno inclusiveField;
    
    public Max() {
        this.inclusiveField = yesno.yes;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(yesno.yes)]
    public yesno inclusive {
        get {
            return this.inclusiveField;
        }
        set {
            this.inclusiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Option {
    
    private Option[] oPTIONField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OPTION")]
    public Option[] OPTION {
        get {
            return this.oPTIONField;
        }
        set {
            this.oPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum ValuesType {
    
    /// <remarks/>
    legal,
    
    /// <remarks/>
    actual,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Link {
    
    private string idField;
    
    private string contentroleField;
    
    private string contenttypeField;
    
    private string titleField;
    
    private string valueField;
    
    private string hrefField;
    
    private string grefField;
    
    private string actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("content-role", DataType="NMTOKEN")]
    public string contentrole {
        get {
            return this.contentroleField;
        }
        set {
            this.contentroleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("content-type", DataType="NMTOKEN")]
    public string contenttype {
        get {
            return this.contenttypeField;
        }
        set {
            this.contenttypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string gref {
        get {
            return this.grefField;
        }
        set {
            this.grefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum dataType {
    
    /// <remarks/>
    boolean,
    
    /// <remarks/>
    bit,
    
    /// <remarks/>
    unsignedByte,
    
    /// <remarks/>
    @short,
    
    /// <remarks/>
    @int,
    
    /// <remarks/>
    @long,
    
    /// <remarks/>
    @char,
    
    /// <remarks/>
    unicodeChar,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    @double,
    
    /// <remarks/>
    floatComplex,
    
    /// <remarks/>
    doubleComplex,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum FieldType {
    
    /// <remarks/>
    hidden,
    
    /// <remarks/>
    no_query,
    
    /// <remarks/>
    trigger,
    
    /// <remarks/>
    location,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Param : Field {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Group {
    
    private anyTEXT dESCRIPTIONField;
    
    private object[] itemsField;
    
    private string idField;
    
    private string nameField;
    
    private string refField;
    
    private string ucdField;
    
    private string utypeField;
    
    /// <remarks/>
    public anyTEXT DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELDref", typeof(FieldRef))]
    [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(Group))]
    [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(Param))]
    [System.Xml.Serialization.XmlElementAttribute("PARAMref", typeof(ParamRef))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class FieldRef {
    
    private string refField;
    
    private string ucdField;
    
    private string utypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class ParamRef {
    
    private string refField;
    
    private string ucdField;
    
    private string utypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string ucd {
        get {
            return this.ucdField;
        }
        set {
            this.ucdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class Resource {
    
    private anyTEXT dESCRIPTIONField;
    
    private Info[] iNFOField;
    
    private object[] itemsField;
    
    private Link[] lINKField;
    
    private object[] items1Field;
    
    private Info[] iNFO1Field;
    
    private System.Xml.XmlElement[] anyField;
    
    private string nameField;
    
    private string idField;
    
    private string utypeField;
    
    private ResourceType typeField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public Resource() {
        this.typeField = ResourceType.results;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public anyTEXT DESCRIPTION {
        get {
            return this.dESCRIPTIONField;
        }
        set {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO", Order=1)]
    public Info[] INFO {
        get {
            return this.iNFOField;
        }
        set {
            this.iNFOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("COOSYS", typeof(CoordinateSystem), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("GROUP", typeof(Group), Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("PARAM", typeof(Param), Order=2)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LINK", Order=3)]
    public Link[] LINK {
        get {
            return this.lINKField;
        }
        set {
            this.lINKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RESOURCE", typeof(Resource), Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("TABLE", typeof(Table), Order=4)]
    public object[] Items1 {
        get {
            return this.items1Field;
        }
        set {
            this.items1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INFO", Order=5)]
    public Info[] INFO1 {
        get {
            return this.iNFO1Field;
        }
        set {
            this.iNFO1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string utype {
        get {
            return this.utypeField;
        }
        set {
            this.utypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ResourceType.results)]
    public ResourceType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public partial class CoordinateSystem {
    
    private string idField;
    
    private string equinoxField;
    
    private string epochField;
    
    private CoordinateSystemSystem systemField;
    
    private string valueField;
    
    public CoordinateSystem() {
        this.systemField = CoordinateSystemSystem.eq_FK5;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string equinox {
        get {
            return this.equinoxField;
        }
        set {
            this.equinoxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string epoch {
        get {
            return this.epochField;
        }
        set {
            this.epochField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(CoordinateSystemSystem.eq_FK5)]
    public CoordinateSystemSystem system {
        get {
            return this.systemField;
        }
        set {
            this.systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum CoordinateSystemSystem {
    
    /// <remarks/>
    eq_FK4,
    
    /// <remarks/>
    eq_FK5,
    
    /// <remarks/>
    ICRS,
    
    /// <remarks/>
    ecl_FK4,
    
    /// <remarks/>
    ecl_FK5,
    
    /// <remarks/>
    galactic,
    
    /// <remarks/>
    supergalactic,
    
    /// <remarks/>
    xy,
    
    /// <remarks/>
    barycentric,
    
    /// <remarks/>
    geo_app,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum ResourceType {
    
    /// <remarks/>
    results,
    
    /// <remarks/>
    meta,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ivoa.net/xml/VOTable/v1.2")]
public enum VOTABLEVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.2")]
    Item12,
}
